csk/urls.py
from django.urls import path
from csk.views import*
app_name='csk'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

rcb/urls.py
from django.urls import path
from rcb.views import*
app_name='rcb'
urlpatterns=[
    path('virat/',virat,name='virat'),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'csk.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'rcb.html')

templates/csk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            this is dhoni page
        </h1>
        <a href="{%  url 'rcb:virat' %}">connect to virat page</a> 
    </center>
    
</body>
</html>

templates/rcb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> this is virat page</h1>
        <a href="{% url 'csk:dhoni' %}">connect to dhoni page</a>
    </center>
</body>
</html>